export const productData = {
  productList: [
    {
      id: "1",
      name: "Green Bag",
      price: 1000,
      category: "Bags",
      gender: "Women",
      URL: "https://images.pexels.com/photos/11124989/pexels-photo-11124989.jpeg",
      discount: "15%",
    },
    {
      id: "2",
      name: "Barbie Purse",
      price: 2000,
      category: "Bags",
      gender: "Women",
      URL: "https://www.nat-nin.com/cdn/shop/products/DANY_CROCPRALINE_V1.webp",
      discount: "25%",
    },
    {
      id: "3",
      name: "Purple Shoulderbag",
      price: 3000,
      category: "Bags",
      gender: "Women",
      URL: "https://img.freepik.com/premium-photo/hand-bag-mockup-white-background_922771-116.jpg?",
      discount: "35%",
    },
    {
      id: "4",
      name: "Tote Bag",
      price: 4000,
      category: "Accesories",
      gender: "Women",
      URL: "https://img.freepik.com/free-photo/colorful-canvas-tote-bag-with-cute-clay-pattern-kids-fashion_53876-125925.jpg?",
      discount: "45%",
    },
    {
      id: "5",
      name: "Card Holder",
      price: 1500,
      category: "Accesories",
      gender: "Women",
      URL: "https://www.nat-nin.com/cdn/shop/files/ALIX_CACAO_V1.webp",
      discount: "15%",
    },
    {
      id: "6",
      name: "Black Boots",
      price: 2000,
      category: "Shoes",
      gender: "Women",
      URL: "https://img.freepik.com/free-photo/shot-elegant-beautiful-leather-heels-isolated-white_181624-32574.jpg?",
      discount: "55%",
    },
    {
      id: "7",
      name: "Red Hot Heels",
      price: 4500,
      category: "Shoes",
      gender: "Women",
      URL: "https://img.freepik.com/premium-photo/red-high-heels-wooman-shooes-3d-rendering_476612-22046.jpg?",
      discount: "25%",
    },
    {
      id: "8",
      name: "Fanny Bag",
      price: 2500,
      category: "Bags",
      gender: "Men",
      URL: "https://www.shutterstock.com/image-photo/mens-black-leather-waist-bag-600nw-1086183635.jpg",
      discount: "15%",
    },
    {
      id: "9",
      name: "Office Bag",
      price: 1500,
      category: "Bags",
      gender: "Men",
      URL: "https://png.pngtree.com/png-vector/20230906/ourmid/pngtree-brown-office-bag-png-image_9997293.png",
      discount: "35%",
    },
    {
      id: "10",
      name: "men's Purse",
      price: 3000,
      category: "Accesories",
      gender: "Men",
      URL: "https://w7.pngwing.com/pngs/737/318/png-transparent-wallet-leather-handbag-zipper-men-s-leather-wallet-brown-fashion-men-suit-thumbnail.png",
      discount: "45%",
    },
    {
      id: "11",
      name: "Duffle bag",
      price: 2000,
      category: "Accesories",
      gender: "Men",
      URL: "https://img.freepik.com/premium-psd/black-bag-logo-mockup-sports-gym-bag_57262-95.jpg?",
      discount: "15%",
    },
    {
      id: "12",
      name: "Black formals ",
      price: 5000,
      category: "Shoes",
      gender: "Men",
      URL: "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg",
      discount: "55%",
    },
    {
      id: "13",
      name: "Men's Sneakers",
      price: 5500,
      category: "Shoes",
      gender: "Men",
      URL: "https://images.pexels.com/photos/3261068/pexels-photo-3261068.jpeg",
      discount: "25%",
    },
  ],
};
